name: CD-SERVER

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-deploy'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Deploy
        run: |
          GITHUB_REF_NAME = ${{ github.ref_name }}
          TAG_VERSION=$(echo ${ GITHUB_REF_NAME//-server/ })
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY_SERVER }}" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_ed25519
          ssh -tt ${{ secrets.SSH }} -i ~/.ssh/id_ed25519 "/home/deployer/web/deploy.sh ${TAG_VERSION} ${{ github.repository_owner }} ${{ secrets.GITHUB_TOKEN }} ${{ github.actor }}"
