name: Deploy to Vercel

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-vercel'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run Linter
        run: yarn lint

      - name: Deploy to Vercel
        run: |
          # Deploy ke Vercel dengan token dan project ID
          npx vercel --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
